server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/api/patients/**

        - id: doctor-service
          uri: lb://doctor-service
          predicates:
            - Path=/api/doctors/**

        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/api/appointments/**

        - id: diagnosis-service
          uri: lb://diagnosis-service
          predicates:
            - Path=/api/diagnoses/**

        - id: ai-service
          uri: lb://ai-service
          predicates:
            - Path=/api/ai/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
