server:
  port: 8083

spring:
  application:
    name: appointment-service

  datasource:
    url: jdbc:postgresql://${APPOINTMENT_DB_HOST:localhost}:${APPOINTMENT_DB_PORT:5435}/${APPOINTMENT_DB:appointment_db}
    username: ${POSTGRES_USER:mediassist_user}
    password: ${POSTGRES_PASSWORD:mediassist_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: false
    open-in-view: false

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:mediassist}
    password: ${RABBITMQ_PASSWORD:rabbit_password}

services:
  patient:
    url: http://localhost:8081
  doctor:
    url: http://localhost:8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
