server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/diagnosis_db
    username: mediassist_user
    password: mediassist_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

patient:
  service:
    url: http://localhost:8081

ai:
  service:
    url: http://localhost:8000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true